<?php

if(isset($_POST['button']) && isset($_FILES['attachment']))
{
	$recipient_email = 'dejan.sheki.lukic@gmail.com, konobakolona@gmail.com'; //from mail, sender email address
	$from_email = 'Konkurs@posao'; //recipient email address
	$subject = 'Posao'; //subject for the email
	
	//Load POST data from HTML form
	$sender_name = $_POST["sender_name"]; //sender name
	$sender_lastname = $_POST['sender_lastname']; 
	$birth_date = date('d-m-y', strtotime($_POST['birth_date']));
	$phone = $_POST['phone'];
	$reply_to_email = $_POST["sender_email"]; //sender email, it will be used in "reply-to" header
    $checked_position = $_POST['position'];
	$message = $_POST["message"]; //body of the email

	if(strlen($sender_name)<1)
	{
		die('Name is too short or empty!');
	}
	//Get uploaded file data using $_FILES array
	$tmp_name = $_FILES['attachment']['tmp_name']; // get the temporary file name of the file on the server
	$name = $_FILES['attachment']['name']; // get the name of the file
	$size = $_FILES['attachment']['size']; // get size of the file for size validation
	$type = $_FILES['attachment']['type']; // get type of the file
	$error = $_FILES['attachment']['error']; // get the error (if any)

	//validate form field for attaching the file
	// if($error > 0)
	// {
	// 	die('Upload error or No files uploaded');
	// }

	//read from the uploaded file & base64_encode content
	$handle = fopen($tmp_name, "r"); // set the file handle only for reading the file
	$content = fread($handle, $size); // reading the file
	fclose($handle);				 // close upon completion

	$encoded_content = chunk_split(base64_encode($content));
	$boundary = md5("random"); // define boundary with a md5 hashed value

	//header
	$headers = "MIME-Version: 1.0\r\n"; // Defining the MIME version
	$headers .= "From:".$from_email."\r\n"; // Sender Email
	$headers .= "Reply-To: ".$reply_to_email."\r\n"; // Email address to reach back
	$headers .= "Content-Type: multipart/mixed;"; // Defining Content-Type
	$headers .= "boundary = $boundary\r\n"; //Defining the Boundary
		
	//plain text
	$body = "--$boundary\r\n";
	$body .= "Content-Type: text/plain; charset=ISO-8859-1\r\n";
	$body .= "Content-Transfer-Encoding: base64\r\n\r\n";
	$body .= chunk_split(base64_encode("Ime: ".$sender_name."\r\n"."Prezime: ".$sender_lastname."\r\n"."Rodjenje: ".$birth_date."\r\n"."Telefon: ".$phone."\r\n"."Pozicija: ".$checked_position."\r\n".$message));
		
	//attachment
	$body .= "--$boundary\r\n";
	$body .="Content-Type: $type; name=".$name."\r\n";
	$body .="Content-Disposition: attachment; filename=".$name."\r\n";
	$body .="Content-Transfer-Encoding: base64\r\n";
	$body .="X-Attachment-Id: ".rand(1000, 99999)."\r\n\r\n";
	$body .= $encoded_content; // Attaching the encoded file with email
	
	$sentMailResult = mail($recipient_email, $subject, $body, $headers);

	if($sentMailResult ){
		echo '<div class="message"><h3>Uspešno ste se prijavili.<h3></div>';
		// unlink($name); // delete the file after attachment sent.
	}
	else{
		die("Sorry but the email could not be sent.
					Please go back and try again!");
	}
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Career</title>
    <link rel="stylesheet" href="../css/career.css" />
    <meta name="description" content="Zapošljavamo! Traže se novi članovi tima za nadolazeću sezonu 2023!">
    <meta name="author" content="Dejan Lukic">
    <meta name="keywords"
        content="Posao, Konobar, Kuhar, Career, Job, Season jobs, Pomocni kuhar, Waiter, Cold kitchen assistant, Warm kitchen assistant">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <meta property="og:type" content="restaurant">
    <meta property="og:title" content="Konoba Kolona | Cavtat">
    <meta property="og:description"
        content="Posao, Konobar, Kuhar, Career, Job, Season jobs, Pomocni kuhar, Waiter, Cold kitchen assistant, Warm kitchen assistant.">
    <meta property="og:url" content="https://konobakolona.com/hr/posao">
    <meta property="og:image" content="https://konobakolona.com/images/welcomephoto.jpg">
    <meta property="og:image:alt" content="Salata od hobotnice">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/menu">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/drinks">
    <meta property="restaurant:contact_info:website" content="https://konobakolona.com">
    <meta property="og:site_name" content="Konoba Kolona">

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Restaurant",
        "name": "Konoba Kolona",
        "image": "https://konobakolona.com/images/welcomephoto.jpg",
        "telephone": "+38520478787",
        "email": "konobakolona@gmail.com",
        "address": {
            "@type": "PostalAddress",
            "addressLocality": "Cavtat"
        },
        "menu": "https://konobakolona.com/hr/menu",
        "servesCuisine": "Morski plodovi",
        "url": "https://konobakolona.com/",
        "priceRange": "$$"
    }
    </script>
</head>

<body>
    <header>
        <div>
            <h1>We are hiring!</h1>
            <p>New members for the upcoming season 2023 wanted!</p>
        </div>
        <div>
            <img src="./images/tiganj-s.jpg" alt="Tiganj" />
            <span>
                Photo by
                <a
                    href="https://unsplash.com/@sevcovic23?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Petr
                    Sevcovic</a>on<a
                    href="https://unsplash.com/photos/e5Q5vWO55uU?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
            </span>
        </div>
    </header>
    <main>
        <section class="positions">
            <div>
                <img src="./images/konobar.jpg" alt="Kuhar" />
            </div>
            <div class="open-positions">
                <h2>Open positions:</h2>
                <h5>Waiter m/f</h5>
                <h5>Cold kitchen assistant m/f</h5>
                <h5>Warm kitchen assistant m/f</h5>
            </div>
        </section>
        <section class="form">
            <h2>Applying procedure</h2>
            <form enctype="multipart/form-data" method="POST" action="">
                <input type="text" name="sender_name" placeholder="Name" required />
                <input type="text" name="sender_lastname" placeholder="Surname" required />
                <input type="text" name="birth_date" placeholder="Date of birth" onfocus="(this.type = 'date')"
                    required />
                <input type="tel" name="phone" placeholder="Phone number" required />
                <input type="email" name="sender_email" placeholder="Email" required />
                <p>The position you're applying to:</p>
                <label for="waiter">
                    <input class="checkbox" type="radio" name="position" id="waiter" value="Konobar" />
                    <span>Waiter</span>
                </label>
                <label for="cold-kitchen">
                    <input class="checkbox" type="radio" name="position" id="cold-kitchen" value="Hladna kuhinja" />
                    <span>Cold kitchen assistant m/f</span>
                </label>
                <label for="hot-kitchen">
                    <input class="checkbox" type="radio" name="position" id="hot-kitchen" value="Topla kuhinja" />
                    <span>Warm kitchen assistant m/f</span>
                </label>
                <textarea name="message" placeholder="Message"></textarea>
                <label for="file">Your CV (optional)</label>
                <input type="file" name="attachment" placeholder="Vaš životopis (opcionalno)" />
                <input type="submit" name="button" value="Send" />
            </form>
        </section>
    </main>
</body>

</html>