<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Konoba Kolona | Cavtat | Menu</title>

    <meta name="description"
        content="Book a table in a restaurant with wide selection of fresh fish, seafood and local wines. We are situated in Cavtat, charming little town with long tradition.">
    <meta name="author" content="Dejan Lukic">
    <meta name="keywords" content="Restaurant, Cavtat, Fish, Food">
    <meta name="robots" content="nofollow">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <meta property="og:type" content="restaurant.menu">
    <meta property="og:title" content="Konoba Kolona | Cavtat | Menu">
    <meta property="og:description"
        content="Book a table in a restaurant with wide selection of fresh fish, seafood and local wines. We are situated in Cavtat, charming little town with long tradition.">
    <meta property="og:url" content="https://konobakolona.com/menu">
    <meta property="og:image" content="https://konobakolona.com/images/welcomephoto.jpg">
    <meta property="restaurant:restaurant" content="https://konobakolona.com">
    <meta property="og:image:alt" content="Octopus salad">
    <meta property="restaurant:contact_info:website" content="https://konobakolona.com">
    <meta property="og:site_name" content="Konoba Kolona">

    <link href="css/style.css" type="text/css" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link href="https://fonts.googleapis.com/css2?family=Varela&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Taviraj:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/ccf2869940.js" crossorigin="anonymous"></script>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Restaurant",
        "name": "Konoba Kolona",
        "image": "https://konobakolona.com/images/welcomephoto.jpg",
        "telephone": "+38520478787",
        "email": "konobakolona@gmail.com",
        "address": {
            "@type": "PostalAddress",
            "addressLocality": "Cavtat"
        },
        "servesCuisine": "Seafood",
        "url": "https://konobakolona.com/menu",
        "priceRange": "$$"
    }
    </script>
</head>

<body>
    <?php include('templates/header.php'); ?>

    <div class="container">

        <div class="contwrap">
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">COLD STARTERS</h2>
                <p class="end menu_span">Fish pâté</p>
                <p class="end menu_price">5 &#8364; &nbsp;<span> (37,67 kn)</span></p>
                <p class="end menu_span">Mixed plate</p>
                <p class="end menu_price">13,50 &#8364; &nbsp;<span> (97,95 kn)</span></p>
                <p class="bracket"> (dalmatian prosciutto & domestic cheese, dried fruits)</p>
                <p class="end menu_span">Octopus salad</p>
                <p class="end menu_price">14 &#8364; &nbsp;<span> (105,48 kn)</span></p>
                <p class="bracket"> (cherry tomatoes, onion, capers)</p>
                <p class="end menu_span">Mozzarella burrata</p>
                <p class="end menu_price">10 &#8364; &nbsp;<span> (75,34 kn)</span></p>
                <p class="bracket"> (tomatoes, basil, olive oil)</p>
                <p class="end menu_span">Fish carpaccio</p>
                <p class="end menu_price">14 &#8364; &nbsp;<span> (105,48 kn)</span></p>
                <p class="bracket"> (aurugula, parmigiano)</p>
                <p class="menu_span">Octopus carpaccio</p>
                <p class="menu_price">14 &#8364; &nbsp;<span> (105,48 kn)</span></p>
                <p class="bracket"> (aurugula, parmigiano)</p>
                <p class="end menu_span">Fish plate</p>
                <p class="end menu_price">15 &#8364; &nbsp;<span> (113 kn)</span></p>
                <p class="bracket"> (bruschette, avocado cream, marinated and smoked fish)</p>
                <p class="end menu_span">Fish tartar</p>
                <p class="end menu_price">13,50 &#8364; &nbsp;<span> (97,95 kn)</span></p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">WARM STARTERS</h2>
                <p class="end menu_span">Mussels buzara</p>
                <p class="end menu_price">14 &#8364; &nbsp;<span> (105,48 kn)</span></p>
                <p class="bracket"> (garlic, white wine, mashed tomatoes)</p>
                <p class="end menu_span">Mixed buzara</p>
                <p class="end menu_price">17 &#8364; &nbsp;<span> (128,08 kn)</span></p>
                <p class="bracket"> (mussels, clams, vongole, prawns)</p>
                <p class="menu_span">Bavette with swordfish and chilli</p>
                <p class="menu_price">15 &#8364; &nbsp;<span> (113 kn)</span></p>
                <p class="menu_span">Black risotto with cuttlefish</p>
                <p class="menu_price">15 &#8364; &nbsp;<span> (113 kn)</span></p>
                <p class="menu_span">Prawns in tempura on arugula, soya souce</p>
                <p class="menu_price">18,50 &#8364; &nbsp;<span> (139,39 kn)</span></p>
                <p class="menu_span">Asparagus and prawn risotto</p>
                <p class="menu_price">15,50 &#8364; &nbsp;<span> (116,78 kn)</span></p>
                <p class="end menu_span">Grilled scampi on a bed of rice in butter</p>
                <p class="end menu_price">23 &#8364; &nbsp;<span> (173,29 kn)</span></p>
                <p class="end menu_span">Scallops fisherman's style</p>
                <p class="end menu_price">17 &#8364; &nbsp;<span> (128,08 kn)</span></p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">SOUPS</h2>
                <p class="menu_span">Fish soup</p>
                <p class="menu_price">7 &#8364; &nbsp;<span> (52,74 kn)</span></p>
                <p class="menu_span">Squash soup with pumpkin seed oil</p>
                <p class="menu_price">7 &#8364; &nbsp;<span> (52,74 kn)</span></p>
                <p class="menu_span">Prawn and zucchini soup</p>
                <p class="menu_price">9 &#8364; &nbsp;<span> (67,81 kn)</span></p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">FISH DISHES</h2>
                <p class="end menu_span">Fresh sea fish (portion)</p>
                <p class="end menu_price">18 &#8364; &nbsp;<span> (135,62 kn)</span></p>
                <p class="end menu_span">Daily fresh sea fish 1kg</p>
                <p class="end menu_price">56 &#8364; &nbsp;<span> (421,93 kn)</span></p>
                <p class="menu_span">Adriatic lobster 1kg</p>
                <p class="menu_price">90 &#8364; &nbsp;<span> (678,10 kn)</span></p>
                <p class="end menu_span">Fish skewers</p>
                <p class="end menu_price">20 &#8364; &nbsp;<span> (150,69 kn)</span></p>
                <p class="bracket">(seasonal vegetables)</p>
                <p class="end menu_span">Grilled squid</p>
                <p class="end menu_price">16 &#8364; &nbsp;<span> (120,55 kn)</span></p>
                <p class="bracket">(swiss chard, potatoes)</p>
                <p class="end menu_span">Fried squid</p>
                <p class="end menu_price">16 &#8364; &nbsp;<span> (120,55 kn)</span></p>
                <p class="bracket">(fried potatoes)</p>
                <p class="end menu_span">Grilled tuna steak</p>
                <p class="end menu_price">20 &#8364; &nbsp;<span> (150,69 kn)</span></p>
                <p class="bracket">(with cuttlefish ink fettuccine)</p>
                <p class="end menu_span">Grilled swordfish steak</p>
                <p class="end menu_price">21 &#8364; &nbsp;<span> (158,22 kn)</span></p>
                <p class="bracket">(with black lentils)</p>
                <p class="end menu_span">Adriatic Seabass filet</p>
                <p class="end menu_price">22 &#8364; &nbsp;<span> (165,75 kn)</span></p>
                <p class="bracket">(seasonal vegetables, celery and fennel cream)</p>
                <p class="end menu_span">Fish platter for two</p>
                <p class="end menu_price">49 &#8364; &nbsp;<span> (369,19 kn)</span></p>
                <p class="bracket">(fresh fish, squid, shrimp, scampi, mixed boiled vegetables)</p>
                <p class="end menu_span">Roasted octopus with potatoes</p>
                <p class="end menu_price">28 &#8364; &nbsp;<span> (210,96 kn)</span></p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">MEAT DISHIES</h2>
                <p class="end menu_span">Beefsteak on the grill 250 g</p>
                <p class="end menu_price">31 &#8364; &nbsp;<span> (233,57 kn)</span></p>
                <p class="bracket">(ratatouille vegetables)</p>
                <p class="end menu_span">Lamb filet 220g</p>
                <p class="end menu_price">33 &#8364; &nbsp;<span> (248,63 kn)</span></p>
                <p class="bracket">(rosemary sauce, julienne vegetables)</p>
                <p class="end menu_span">Filet mignon 200g</p>
                <p class="end menu_price">27 &#8364; &nbsp;<span> (203,43 kn)</span></p>
                <p class="bracket">(red wine sauce, ratatouille vegetables)</p>
                <p class="end menu_span">Duck breasts</p>
                <p class="end menu_price">25 &#8364; &nbsp;<span> (188,36 kn)</span></p>
                <p class="bracket">(squash purre, grilled vegetables)</p>
                <p class="end menu_span">Pork medallions</p>
                <p class="end menu_price">17 &#8364; &nbsp;<span> (128,08 kn)</span></p>
                <p class="bracket">(gnocchi in plum sauce)</p>
            </div>
            <div class="menu" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">VEGETARIAN DISHES</h2>
                <p class="end menu_span">Vegetable risotto</p>
                <p class="end menu_price">10 &#8364; &nbsp;<span> (75,34 kn)</span></p>
                <p class="end menu_span">Grilled vegetables with mozzarella</p>
                <p class="end menu_price">12 &#8364; &nbsp;<span> (90,41 kn)</span></p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">CHILDREN'S MENU</h2>
                <p class="menu_span">Grilled chicken breasts with french fries</p>
                <p class="menu_price">12 &#8364; &nbsp;<span> (90,41 kn)</span></p>
                <p class="menu_span">Spaghetti Bolognese</p>
                <p class="menu_price">9,50 &#8364; &nbsp;<span> (71,58 kn)</span></p>
                <p class="menu_span">Spaghetti Napolitana</p>
                <p class="menu_price">8 &#8364; &nbsp;<span> (60,27 kn)</span></p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">SALADS</h2>
                <p class="end menu_span">Seasonal salad</p>
                <p class="end menu_price">4,50 &#8364; &nbsp;<span> (33,90 kn)</span></p>
                <p class="end menu_span">Greek salad</p>
                <p class="end menu_price">7 &#8364; &nbsp;<span> (52,74 kn)</span></p>
                <p class="end menu_span">Chef's salad</p>
                <p class="end menu_price">9 &#8364; &nbsp;<span> (67,81 kn)</span></p>
                <p class="bracket">(cucumbers, aurugula, chicory, spinach, cycle, riccota cheese, pine nuts)</p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">SIDE DISHES</h2>
                <p class="menu_span">Swiss chard and boiled potatoes</p>
                <p class="menu_price">6 &#8364; &nbsp;<span> (45,20 kn)</span></p>
                <p class="menu_span">Mixed seasonal vegetables</p>
                <p class="menu_price">6 &#8364; &nbsp;<span> (45,20 kn)</span></p>
                <p class="menu_span">French fries</p>
                <p class="menu_price">6 &#8364; &nbsp;<span> (45,20 kn)</span></p>
                <p class="menu_span">Baker's potatoes</p>
                <p class="menu_price">6 &#8364; &nbsp;<span> (45,20 kn)</span></p>
                <p class="menu_span">Rice in butter</p>
                <p class="menu_price">6 &#8364; &nbsp;<span> (45,20 kn)</span></p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">DESERTS</h2>
                <p class="menu_span">Dubrovnik style rosata (créme caramel)</p>
                <p class="menu_price">7 &#8364; &nbsp;<span> (52,74 kn)</span></p>
                <p class="menu_span">Ice cream (3 scoops)</p>
                <p class="menu_price">5 &#8364; &nbsp;<span> (37,67 kn)</span></p>
                <p class="menu_span">Pannacotta</p>
                <p class="menu_price">7 &#8364; &nbsp;<span> (52,74 kn)</span></p>
                <p class="menu_span">Homemade chocolate cake with carob</p>
                <p class="menu_price">7 &#8364; &nbsp;<span> (52,74 kn)</span></p>
            </div>
        </div>
        <?php include('templates/footer.php'); ?>
    </div>
    <script type="text/javascript" src="script/main.js"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <?php 
    
    $useragent = $_SERVER['HTTP_USER_AGENT']; 
    $iPod = stripos($useragent, "iPod"); 
    $iPad = stripos($useragent, "iPad"); 
    $iPhone = stripos($useragent, "iPhone"); 
    $iOS = stripos($useragent, "iOS");
    $iPadOS = stripos($useragent,"Macintosh");


    $DEVICE = ($iPod||$iPad||$iPhone||$iOS||$iPadOS);

    if (!$DEVICE) { ?>

    <script>
    AOS.init();
    </script>

    <?php }else{ 
    ?>

    <script>
    AOS.init({
        disable: true
    });
    </script>

    <?php } ?>
</body>

</html>