<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Konoba Kolona | Cavtat | Vinska karta</title>

    <meta name="description" content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
    <meta name="author" content="Dejan Lukic">
    <meta name="keywords" content="Restoran, Cavtat, Vino, Riba">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
    <meta property="og:type" content="restaurant">
    <meta property="og:title" content="Konoba Kolona | Cavtat">
    <meta property="og:description" content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
    <meta property="og:url" content="https://konobakolona.com/hr/drinks">
    <meta property="og:image" content="https://konobakolona.com/images/welcomephoto.jpg">
    <meta property="og:image:alt" content="Salata od hobotnice">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/menu">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/drinks">
    <meta property="restaurant:contact_info:website" content="https://konobakolona.com">
    <meta property="og:site_name" content="Konoba Kolona">

    <link href="../css/style.css" type="text/css" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link href="https://fonts.googleapis.com/css2?family=Varela&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Taviraj:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"> 

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/ccf2869940.js" crossorigin="anonymous"></script>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "Restaurant",
      "name" : "Konoba Kolona",
      "image" : "https://konobakolona.com/images/welcomephoto.jpg",
      "telephone" : "+38520478787",
      "email" : "konobakolona@gmail.com",
      "address" : {
        "@type" : "PostalAddress",
        "addressLocality" : "Cavtat"
      },
      "menu" : "https://konobakolona.com/hr/menu",
      "servesCuisine" : "Morski plodovi",
      "url" : "https://konobakolona.com/",
      "priceRange":"$$"
    }
    </script>
</head>
<body>
	<?php include('../templates/header_hr.php'); ?>

	<div class="container">
        
		<div class="contwrap">
			<div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">STOLNO BIJELO VINO</h2>
                <p class="menu_span">Stolno – 1,00<i>l</i></p><p class="menu_price">150,00 kn</p>
                <p class="menu_span">Pošip Čara – 1,00<i>l</i></p><p class="menu_price">170,00 kn</p>
                <p class="menu_span">Maraština – 0,75<i>l</i></p><p class="menu_price">160,00 kn</p>
            </div>	
			<div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">BIJELO VINO NA ČAŠE</h2>
                <p class="menu_span">Stolno – 0,20<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Pošip Čara – 0,20<i>l</i></p><p class="menu_price">34,00 kn</p>
                <p class="menu_span">Malvasija Dubrovačka – 0,15<i>l</i></p><p class="menu_price">48,00 kn</p>
                <p class="menu_span">Chardonay – 0,15<i>l</i></p><p class="menu_price">48,00 kn</p>
                <p class="menu_span">Rosé Cuvée – 0,15<i>l</i></p><p class="menu_price">45,00 kn</p>
            </div>		
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">SORTNO BIJELO VINO</h2>
                <p class="menu_span">Malvasija Dubrovačka – 0,75<i>l</i></p><p class="menu_price">240,00 kn</p>
                <p class="menu_span">Malvasija Dubrovačka Royal <i>sur lie</i> – 0,75<i>l</i></p><p class="menu_price">260,00 kn</p>
                <p class="menu_span">Malvasija Kozlović – 0,75<i>l</i></p><p class="menu_price">270,00 kn</p>
                <p class="menu_span">Pošip Grgić – 0,75<i>l</i></p><p class="menu_price">370,00 kn</p>
                <p class="menu_span">Pošip Čara – 0,75<i>l</i></p><p class="menu_price">220,00 kn</p>
                <p class="menu_span">Pošip Intrada – 0,75<i>l</i></p><p class="menu_price">270,00 kn</p>
                <p class="menu_span">Graševina Krauthaker – 0,75<i>l</i></p><p class="menu_price">220,00 kn</p>
                <p class="menu_span">Traminac Iločki – 0,75<i>l</i></p><p class="menu_price">240,00 kn</p> 
                <p class="menu_span">Chardonay – 0,75<i>l</i></p><p class="menu_price">240,00 kn</p>
                <p class="menu_span">Vrbnička Žlahtina – 0,75<i>l</i></p><p class="menu_price">200,00 kn</p>               
                <p class="menu_span">Pinot Sivi Krauthaker – 0,75<i>l</i></p><p class="menu_price">190,00 kn</p>
                <p class="menu_span">Sauvignon blanc Iuris – 0,75<i>l</i></p><p class="menu_price">225,00 kn</p>
                <p class="menu_span">Rose Krauthaker – 0,75<i>l</i></p><p class="menu_price">225,00 kn</p>
                <p class="menu_span">Graševina – 0,187<i>l</i></p><p class="menu_price">35,00 kn</p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">PRIRODNI PJENUŠAC</h2>
                <p class="menu_span">Tomac Millenium Brut – 0,75<i>l</i></p><p class="menu_price">350,00 kn</p>
                <p class="menu_span">Prosecco – 0,20<i>l</i></p><p class="menu_price">60,00 kn</p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">STOLNO CRNO VINO</h2>
                <p class="menu_span">Stolno – 1,00<i>l</i></p><p class="menu_price">150,00 kn</p>
                <p class="menu_span">Pelješac – 1,00<i>l</i></p><p class="menu_price">170,00 kn</p>
            </div>	
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">CRNO VINO NA ČAŠE</h2>
                <p class="menu_span">Stolno – 0,20<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Pelješac – 0,20<i>l</i></p><p class="menu_price">34,00 kn</p>
                <p class="menu_span">Plavac Mali – 0,15<i>l</i></p><p class="menu_price">44,00 kn</p>
                <p class="menu_span">Dingač Miličić – 0,15<i>l</i></p><p class="menu_price">55,00 kn</p>
                <p class="menu_span">Negromanat (Merlot) – 0,15<i>l</i></p><p class="menu_price">40,00 kn</p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">SORTNO CRNO VINO</h2>
                <p class="menu_span">Plavac Grgić – 0,75<i>l</i></p><p class="menu_price">360,00 kn</p>
                <p class="menu_span">Dingač Miličić – 0,75<i>l</i></p><p class="menu_price">275,00 kn</p>
                <p class="menu_span">Postup Potonje – 0,75<i>l</i></p><p class="menu_price">250,00 kn</p>
                <p class="menu_span">Plavac Mali DP – 0,75<i>l</i></p><p class="menu_price">220,00 kn</p>
                <p class="menu_span">Zlatan plavac Plenković – 0,75<i>l</i></p><p class="menu_price">250,00 kn</p>
                <p class="menu_span">Pomet (Plavac Mali) Crvik – 0,75<i>l</i></p><p class="menu_price">250,00 kn</p>
                <p class="menu_span">Negromant (Merlot) – 0,75<i>l</i></p><p class="menu_price">250,00 kn</p>
                <p class="menu_span">Cabernet Sauvignon – 0,75<i>l</i></p><p class="menu_price">180,00 kn</p> 
                <p class="menu_span">Pinot crni – 0,75<i>l</i></p><p class="menu_price">280,00 kn</p>
            </div>	
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">DESERTNO VINO</h2>
                <p class="menu_span">Muškat Kozlović – 0,50<i>l</i></p><p class="menu_price">250,00 kn</p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">APERITIVI</h2>
                <p class="menu_span">Amaro – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Istra Bitter – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Vermouth – 0,10<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Prošek Hektorović – 0,10<i>l</i></p><p class="menu_price">60,00 kn</p>
                <p class="menu_span">Martini Dry – 0,10<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Martini Bianco – 0,10<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Martini Rosso – 0,10<i>l</i></p><p class="menu_price">30,00 kn</p>
            </div>	
            <div class="menu" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">DOMAĆA ALKOHOLNA PIĆA</h2>
                <p class="menu_span">Lozovača – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Travarica – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Šljivovica – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Viljamovka – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Zvečevo Konjak – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Pelinkovac – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Vlahovac – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Apricot – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Kruškovac – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Maraschino – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Stock – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Rum – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Gin – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Vodka – 0,03<i>l</i></p><p class="menu_price">25,00 kn</p>
            </div>	
            <div class="menu" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">STRANA ALKOHOLNA PIĆA</h2>
                <p class="menu_span">Chivas Regal – 0,03<i>l</i></p><p class="menu_price">50,00 kn</p>
                <p class="menu_span">Jack Daniel's – 0,03<i>l</i></p><p class="menu_price">37,00 kn</p>
                <p class="menu_span">Johnnie Walker – 0,03<i>l</i></p><p class="menu_price">37,00 kn</p>
                <p class="menu_span">Ballantine's – 0,03<i>l</i></p><p class="menu_price">37,00 kn</p>
                <p class="menu_span">Jameson – 0,03<i>l</i></p><p class="menu_price">37,00 kn</p>
                <p class="menu_span">Martell – 0,03<i>l</i></p><p class="menu_price">50,00 kn</p>
                <p class="menu_span">Rémy Martin – 0,03<i>l</i></p><p class="menu_price">50,00 kn</p>
                <p class="menu_span">Hennessy – 0,03<i>l</i></p><p class="menu_price">50,00 kn</p>
                <p class="menu_span">Cointreau – 0,03<i>l</i></p><p class="menu_price">37,00 kn</p>
                <p class="menu_span">Tia Maria – 0,03<i>l</i></p><p class="menu_price">37,00 kn</p>
                <p class="menu_span">Amaretto – 0,03<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Tequila – 0,03<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Bacardi – 0,03<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Baileys – 0,03<i>l</i></p><p class="menu_price">35,00 kn</p>
                <p class="menu_span">Campari – 0,03<i>l</i></p><p class="menu_price">35,00 kn</p>
                <p class="menu_span">Beefeater Gin – 0,03<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Drambuie – 0,03<i>l</i></p><p class="menu_price">35,00 kn</p>
                <p class="menu_span">Jägermeister – 0,03<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Smirnoff Vodka – 0,03<i>l</i></p><p class="menu_price">35,00 kn</p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">PIVO</h2>
                <p class="menu_span">Ožujsko – 0,33<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Karlovačko – 0,33<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Karlovačko Radler – 0,33<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Heineken – 0,33<i>l</i></p><p class="menu_price">40,00 kn</p>
                <p class="menu_span">Erdinger Weissbier – 0,50<i>l</i></p><p class="menu_price">40,00 kn</p>
                <p class="menu_span">Grička vještica – 0,33<i>l</i></p><p class="menu_price">35,00 kn</p>
                <p class="menu_span">Karlovačko bezalkoholno – 0,50<i>l</i></p><p class="menu_price">35,00 kn</p>
                <p class="menu_span">Točeno pivo – 0,30<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Točeno pivo – 0,50<i>l</i></p><p class="menu_price">35,00 kn</p>
            </div>
            <div class="menu" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">HLADNI NAPITCI</h2>
                <p class="menu_span">Coca Cola – 0,25<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Fanta – 0,25<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Sprite – 0,25<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="end menu_span">Schweppes – 0,25<i>l</i></p><p class="end menu_price">25,00 kn</p><p class="bracket">(Bitter Lemon, Tonic, Tangerina)</p>
                <p class="menu_span">Orangina – 0,20<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Cockta – 0,20<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Voćni sokovi – 0,20<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Voćni sok borovnica – 0,20<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Cijeđena limunada – 0,20<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Cijeđena narančada – 0,20<i>l</i></p><p class="menu_price">30,00 kn</p>
                <p class="menu_span">Gazirana mineralna voda – 1,00<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Gazirana mineralna voda – 0,50<i>l</i></p><p class="menu_price">22,00 kn</p>
                <p class="menu_span">Prirodna mineralna voda – 0,75<i>l</i></p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Prirodna mineralna voda – 0,25<i>l</i></p><p class="menu_price">15,00 kn</p>
            </div>	
            <div class="menu" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">TOPLI NAPITCI</h2>
                <p class="menu_span">Espresso (šalica)</p><p class="menu_price">12,00 kn</p>
                <p class="menu_span">Macchiato (šalica)</p><p class="menu_price">14,00 kn</p>
                <p class="menu_span">Bijela kava (šalica)</p><p class="menu_price">20,00 kn</p>
                <p class="menu_span">Cappuccino (šalica)</p><p class="menu_price">20,00 kn</p>
                <p class="menu_span">Kakao (šalica)</p><p class="menu_price">20,00 kn</p>
                <p class="menu_span">Čaj (šalica)</p><p class="menu_price">20,00 kn</p>
                <p class="menu_span">Ledena kava (šalica)</p><p class="menu_price">25,00 kn</p>
                <p class="menu_span">Nescafé (šalica)</p><p class="menu_price">20,00 kn</p>
                <p class="menu_span">Mlijeko (šalica)</p><p class="menu_price">12,00 kn</p>
            </div>			
		</div>
			<?php include('../templates/footer.php'); ?>
	</div>
		<script type="text/javascript" src="../script/main.js"></script>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<?php 
    
    $useragent = $_SERVER['HTTP_USER_AGENT']; 
    $iPod = stripos($useragent, "iPod"); 
    $iPad = stripos($useragent, "iPad"); 
    $iPhone = stripos($useragent, "iPhone"); 
    $iOS = stripos($useragent, "iOS");
    $iPadOS = stripos($useragent,"Macintosh");


    $DEVICE = ($iPod||$iPad||$iPhone||$iOS||$iPadOS);

    if (!$DEVICE) { ?>

    <script>
         AOS.init();
    </script>

<?php }else{ 
    ?> 

    <script>
        AOS.init({disable:true});
    </script>

<?php } ?>
</body>
</html>