<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Konoba Kolona | Cavtat | Galerija</title>

    <meta name="description" content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
	<meta name="keywords" content="Riblji Restoran, Cavtat, Morski plodovi, Jastog">
    <meta name="author" content="Dejan Lukic">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
    <meta property="og:type" content="restaurant">
    <meta property="og:title" content="Konoba Kolona | Cavtat">
    <meta property="og:description" content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
    <meta property="og:url" content="https://konobakolona.com/hr/gallery">
    <meta property="og:image" content="https://konobakolona.com/images/welcomephoto.jpg">
    <meta property="og:image:alt" content="Salata od hobotnice">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/menu">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/drinks">
    <meta property="restaurant:contact_info:website" content="https://konobakolona.com">
    <meta property="og:site_name" content="Konoba Kolona">

	<link href="../css/style.css" type="text/css" rel="stylesheet">
	<link href="../css/gallery.css" type="text/css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link href="https://fonts.googleapis.com/css2?family=Varela&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Taviraj:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"> 

    <script src="https://kit.fontawesome.com/ccf2869940.js" crossorigin="anonymous"></script>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "Restaurant",
      "name" : "Konoba Kolona",
      "image" : "https://konobakolona.com/images/welcomephoto.jpg",
      "telephone" : "+38520478787",
      "email" : "konobakolona@gmail.com",
      "address" : {
        "@type" : "PostalAddress",
        "addressLocality" : "Cavtat"
      },
      "menu" : "https://konobakolona.com/hr/menu",
      "servesCuisine" : "Morski plodovi",
      "url" : "https://konobakolona.com/",
      "priceRange":"$$"
    }
    </script>
 
</head>
<body>
	<?php include('../templates/header_hr.php'); ?>
	<div class="gallerycontainer">
	<div class="gallery">
		<div class="gallitem_8">
			<img data-enlargable src="../images/slika1.jpg" alt="Restoran Konoba Kolona" title="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_2">
			<img data-enlargable src="../images/slika2.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_6">
			<img data-enlargable src="../images/slika3.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_7">
			<img data-enlargable src="../images/slika4.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_5">
			<img data-enlargable src="../images/slika5.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_dod1">
			<img data-enlargable src="../images/dodatak1.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_9">
			<img data-enlargable src="../images/slika6.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_10">
			<img data-enlargable src="../images/slika7.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_11">
			<img data-enlargable src="../images/slika8.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_12">
			<img data-enlargable src="../images/slika9.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_13">
			<img data-enlargable src="../images/slika10.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_14">
			<img data-enlargable src="../images/slika11.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_15">
			<img data-enlargable src="../images/slika12.jpg" alt="Konoba Kolona">
		</div>
		<div class="gallitem_1">
			<img data-enlargable src="../images/slika13.jpg" alt="Konoba Kolona">
		</div>
		<div class="gallitem_4">
			<img data-enlargable src="../images/slika14.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_3">
			<img data-enlargable src="../images/slika15.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_dod2">
			<img data-enlargable src="../images/dodatak2.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_16">
			<img data-enlargable src="../images/pogled1.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_17">
			<img data-enlargable src="../images/pogled2.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_18">
			<img data-enlargable src="../images/spoljasnost1.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_19">
			<img data-enlargable src="../images/spoljasnost2.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_dod3">
			<img data-enlargable src="../images/dodatak3.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_20">
			<img data-enlargable src="../images/spoljasnost3.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_21">
			<img data-enlargable src="../images/hrana5.jpg" alt="Ljetna salata">
		</div>
		<div class="gallitem_22">
			<img data-enlargable src="../images/hrana8.jpg" alt="Riblji pjat">
		</div>
		<div class="gallitem_23">
			<img data-enlargable src="../images/hrana7.jpg" alt="Mozzarella burrata">
		</div>
		<div class="gallitem_24">
			<img data-enlargable src="../images/hrana17.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_25">
			<img data-enlargable src="../images/hrana9.jpg" alt="Pačja prsa">
		</div>
		<div class="gallitem_26">
			<img data-enlargable src="../images/hrana11.jpg" alt="Riblji pjat">
		</div>
		<div class="gallitem_27">
			<img data-enlargable src="../images/hrana10.jpg" alt="Pačja prsa">
		</div>
		<div class="gallitem_28">
			<img data-enlargable src="../images/hrana12.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_29">
			<img data-enlargable src="../images/hrana14.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_30">
			<img data-enlargable src="../images/hrana6.jpg" alt="Riblji carpaccio">
		</div>
		<div class="gallitem_31">
			<img data-enlargable src="../images/hrana1.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_32">
			<img data-enlargable src="../images/hrana2.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_33">
			<img data-enlargable src="../images/hrana3.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_34">
			<img data-enlargable src="../images/hrana4.jpg" alt="Škamp i školjke">
		</div>
		<div class="gallitem_35">
			<img data-enlargable src="../images/hrana13.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_36">
			<img data-enlargable src="../images/hrana16.jpg" alt="Hladna plitica">
		</div>
		<div class="gallitem_37">
			<img data-enlargable src="../images/hrana18.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_38">
			<img data-enlargable src="../images/hrana15.jpg" alt="Naši škoji">
		</div>
		<div class="gallitem_39">
			<img data-enlargable src="../images/hrana21.jpg" alt="Riblji pjat">
		</div>
		<div class="gallitem_40">
			<img data-enlargable src="../images/hrana19.jpg" alt="Restoran Konoba Kolona">
		</div>
		<div class="gallitem_41">
			<img data-enlargable src="../images/hrana22.jpg" alt="Hobotnica na salatu">
		</div>
		<div class="gallitem_42">
			<img data-enlargable src="../images/hrana23.jpg" alt="Hobotnica">
		</div>
		<div class="gallitem_43">
			<img data-enlargable src="../images/hrana20.jpg" alt="Riblji carpaccio">
		</div>
		<div class="gallitem_45">
			<img data-enlargable src="../images/riba1.jpg" alt="Riba">
		</div>
		<div class="gallitem_47">
			<img data-enlargable src="../images/riba2.jpg" alt="Riba">
		</div>
		<div class="gallitem_46">
			<img data-enlargable src="../images/riba3.jpg" alt="Riba">
		</div>
		<div class="gallitem_48">
			<img data-enlargable src="../images/riba4.jpg" alt="Riba">
		</div>
		<div class="gallitem_44">
			<img data-enlargable src="../images/riba5.jpg" alt="Riba">
		</div>
		<div class="gallitem_49">
			<img data-enlargable src="../images/riba6.jpg" alt="Riba">
		</div>
		<div class="gallitem_50">
			<img data-enlargable src="../images/riba7.jpg" alt="Riba">
		</div>
		<div class="gallitem_51">
			<img data-enlargable src="../images/ribanje1.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_52">
			<img data-enlargable src="../images/ribanje2.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_53">
			<img data-enlargable src="../images/ribanje3.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_54">
			<img data-enlargable src="../images/ribanje4.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_55">
			<img data-enlargable src="../images/ribanje5.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_56">
			<img data-enlargable src="../images/ribanje6.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_57">
			<img data-enlargable src="../images/ribanje7.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_58">
			<img data-enlargable src="../images/ribanje8.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_59">
			<img data-enlargable src="../images/ribanje9.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_60">
			<img data-enlargable src="../images/ribanje10.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_61">
			<img data-enlargable src="../images/ribanje11.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_62">
			<img data-enlargable src="../images/ribanje12.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_63">
			<img data-enlargable src="../images/ribanje13.jpg" alt="Ribanje Konoba Kolona">
		</div>
		<div class="gallitem_64">
			<img data-enlargable src="../images/ribanje14.jpg" alt="Ribanje Konoba Kolona">
		</div>
	</div>
	</div>
	<?php include('../templates/footer.php'); ?>
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="../script/main.js"></script>
	<script type="text/javascript" src="../script/gallery.js"></script>
</body>
</html>