<!DOCTYPE html>
<html lang="hr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Konoba Kolona | Cavtat | Jelovnik</title>

    <meta name="description"
        content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
    <meta name="author" content="Dejan Lukic">
    <meta name="keywords" content="Restaurant, Cavtat, Fish, Food">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <meta property="og:type" content="restaurant">
    <meta property="og:title" content="Konoba Kolona | Cavtat">
    <meta property="og:description"
        content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
    <meta property="og:url" content="https://konobakolona.com/hr/menu">
    <meta property="og:image" content="https://konobakolona.com/images/welcomephoto.jpg">
    <meta property="og:image:alt" content="Salata od hobotnice">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/menu">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/drinks">
    <meta property="restaurant:contact_info:website" content="https://konobakolona.com">
    <meta property="og:site_name" content="Konoba Kolona">

    <link href="../css/style.css" type="text/css" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link href="https://fonts.googleapis.com/css2?family=Varela&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Taviraj:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/ccf2869940.js" crossorigin="anonymous"></script>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Restaurant",
        "name": "Konoba Kolona",
        "image": "https://konobakolona.com/images/welcomephoto.jpg",
        "telephone": "+38520478787",
        "email": "konobakolona@gmail.com",
        "address": {
            "@type": "PostalAddress",
            "addressLocality": "Cavtat"
        },
        "menu": "https://konobakolona.com/hr/menu",
        "servesCuisine": "Morski plodovi",
        "url": "https://konobakolona.com/",
        "priceRange": "$$"
    }
    </script>
</head>

<body>
    <?php include('../templates/header_hr.php'); ?>
    <div class="container">
        <div class="contwrap">
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">HLADNA PREDJELA</h2>
                <p class="end menu_span">Riblja pašteta</p>
                <p class="end menu_price">36 kn / 4.80 EUR</p>
                <p class="end menu_span">Miješana plitica</p>
                <p class="end menu_price">95 kn /12.60 EUR</p>
                <p class="bracket">(dalmatinski pršut, domaći sir, rikula, suho voće)</p>
                <p class="end menu_span">Hobotnica na salatu</p>
                <p class="end menu_price">95 kn / 12.60 EUR</p>
                <p class="end menu_span">Mozzarella burrata</p>
                <p class="end menu_price">70 kn / 9.30 EUR</p>
                <p class="end menu_span">Riblji carpaccio</p>
                <p class="end menu_price">95 kn /12.60 EUR</p>
                <p class="end menu_span">Carpaccio od hobotnice</p>
                <p class="end menu_price">95 kn / 12.60 EUR</p>
                <p class="end menu_span">Riblji pjat</p>
                <p class="end menu_price">115 kn / 15.30 EUR</p>
                <p class="bracket">(bruschette, avokado krema, marinirana i dimljena riba)</p>
                <p class="end menu_span">Tartar od svježe ribe</p>
                <p class="end menu_price">90 kn / 11.95 EUR</p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">TOPLA PREDJELA</h2>
                <p class="end menu_span">Mušule na buzaru</p>
                <p class="end menu_price">90 kn / 11.95 EUR</p>
                <p class="bracket">(češnjak, bijelo vino, sjeckane rajčice)</p>
                <p class="end menu_span">Miješana buzara</p>
                <p class="end menu_price">120 kn / 15.90 EUR</p>
                <p class="menu_span">Bavette sa sabljarkom</p>
                <p class="menu_price">95 kn / 12.60 EUR</p>
                <p class="bracket">(chilli)</p>
                <p class="menu_span">Crni rižot od sipe</p>
                <p class="menu_price">95 kn / 12.60 EUR</p>
                <p class="menu_span">Gambori u tempuri na rikuli</p>
                <p class="menu_price">130 kn / 17.25 EUR</p>
                <p class="menu_span">Rižot s kozicama i šparogama</p>
                <p class="menu_price">105 kn / 13.90 EUR</p>
                <p class="menu_span">Škampi žar s rižom</p>
                <p class="menu_price">170 kn / 22.56 EUR</p>
                <p class="menu_span">Ravioli s ovčjim sirom i rezancima bifteka</p>
                <p class="menu_price">95 kn /12.60 EUR</p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">JUHE</h2>
                <p class="menu_span">Riblja juha</p>
                <p class="menu_price">48 kn / 6.40 EUR</p>
                <p class="menu_span">Juha od tikve s bučinim uljem</p>
                <p class="menu_price">48 kn / 6.40 EUR</p>
                <p class="menu_span">Dnevna juha</p>
                <p class="menu_price">36 kn / 4.80 EUR</p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">RIBLJA JELA</h2>
                <p class="end menu_span">Svježa morska riba 1kg</p>
                <p class="end menu_price">420 kn /55.70 EUR</p>
                <p class="menu_span">Jadranski jastog 1kg</p>
                <p class="menu_price">700 kn / 92.90 EUR</p>
                <p class="end menu_span">Riblji ražnjići</p>
                <p class="end menu_price">150 kn / 19.90 EUR</p>
                <p class="bracket">(riba, lignji, kozice)</p>
                <p class="end menu_span">Lignji sa žara</p>
                <p class="end menu_price">120 kn / 15.90 EUR</p>
                <p class="bracket">(blitva, krumpir)</p>
                <p class="end menu_span">Lignji prženi</p>
                <p class="end menu_price">120 kn / 15.90 EUR</p>
                <p class="bracket">(prženi krumpir)</p>
                <p class="end menu_span">Filet tune sa žara</p>
                <p class="end menu_price">150 kn / 19.90 EUR</p>
                <p class="bracket">(tikvice, mahune)</p>
                <p class="end menu_span">Filet sabljarke s mariniranom rajčicom</p>
                <p class="end menu_price">160 kn / 21.20 EUR</p>
                <p class="bracket">(miješano kuhano povrće)</p>
                <p class="end menu_span">Filet jadranskog brancina</p>
                <p class="end menu_price">150 kn /19.90 EUR</p>
                <p class="bracket">(krema od celera i komorača, šparoge na maslacu)</p>
                <p class="end menu_span">Riblja plata za 2 osobe</p>
                <p class="end menu_price">370 kn / 49.10 EUR</p>
                <p class="bracket">(svježa riba, lignji, kozice, škampi s kuhanim povrćem)</p>
                <p class="end menu_span">Pečena hobotnica s krumpirom</p>
                <p class="end menu_price">170 kn / 22.60 EUR</p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">MESNA JELA</h2>
                <p class="end menu_span">Biftek na žaru 250g</p>
                <p class="end menu_price">230 kn / 30 EUR</p>
                <p class="bracket">(ratatouille povrće, krumpir)</p>
                <p class="end menu_span">Janjeći filet 220g</p>
                <p class="end menu_price">240 kn / 31.85 EUR</p>
                <p class="bracket">(umak od ružmarina, julienne povrće, krumpir)</p>
                <p class="end menu_span">Filet mignon 200g</p>
                <p class="end menu_price">200 kn / 26.50 EUR</p>
                <p class="bracket">(umak od crnog vina, ratatouille povrće, krumpir)</p>
                <p class="end menu_span">Pačja prsa</p>
                <p class="end menu_price">170 kn / 22.60 EUR</p>
                <p class="bracket">(krema od tikve, povrće sa žara)</p>
                <p class="end menu_span">Svinjski medaljoni</p>
                <p class="end menu_price">130 kn / 17.25 EUR</p>
                <p class="bracket">(umak od šljiva, njoki)</p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">VEGETARIJANSKA JELA</h2>
                <p class="end menu_span">Rižot od povrća</p>
                <p class="end menu_price">75 kn / 9.95 EUR</p>
                <p class="end menu_span">Povrće žar s mozzarelom</p>
                <p class="end menu_price">90 kn / 11.95 EUR</p>
                <p class="end menu_span">Istarski fuži s šampinjonima i sušenim vrganjima</p>
                <p class="end menu_price">95 kn / 12.60 EUR</p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">SALATE</h2>
                <p class="end menu_span">Sezonska salataa</p>
                <p class="end menu_price">35 kn / 4.65 EUR</p>
                <p class="end menu_span">Grčka salata</p>
                <p class="end menu_price">50 kn /6.65 EUR</p>
                <p class="end menu_span">Salata šefa kuhinje</p>
                <p class="end menu_price">60 kn / 8 EUR</p>
                <p class="bracket">(krastavci, rikula, radič, špinat, cikla, riccota sir, pinjoli, cherry rajčica)</p>
            </div>
            <div class="menu" data-aos="zoom-in-up" data-aos-duration="1500">
                <h2 class="center">DJEČJI MENI</h2>
                <p class="menu_span">Piletina sa žara s prženim krumpirićima</p>
                <p class="menu_price">85 kn / 11.30 EUR</p>
                <p class="menu_span">Špageti Bolognese</p>
                <p class="menu_price">65 kn / 8.60 EUR</p>
                <p class="menu_span">Špageti Napolitana</p>
                <p class="menu_price">55 kn / 7.30 EUR</p>
                <p class="menu_span">Prženi krumpirići</p>
                <p class="menu_price">35 kn / 4.65 EUR</p>
            </div>
            <div class="menu dessert" data-aos="zoom-in" data-aos-duration="1500">
                <h2 class="center">DESERTI</h2>
                <p class="menu_span">Dubrovačka rozata</p>
                <p class="menu_price">50 kn / 6.65 EUR</p>
                <p class="menu_span">Sladoled</p>
                <p class="menu_price">36 kn / 4.80 EUR</p>
                <p class="menu_span">Pannacotta</p>
                <p class="menu_price">50 kn / 6.65 EUR</p>
                <p class="menu_span">Torta od rogača i čokolade</p>
                <p class="menu_price">55 kn / 7.30 EUR</p>
            </div>
        </div>
        <?php include('../templates/footer.php'); ?>
    </div>
    <script type="text/javascript" src="../script/main.js"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <?php 
    
    $useragent = $_SERVER['HTTP_USER_AGENT']; 
    $iPod = stripos($useragent, "iPod"); 
    $iPad = stripos($useragent, "iPad"); 
    $iPhone = stripos($useragent, "iPhone"); 
    $iOS = stripos($useragent, "iOS");
    $iPadOS = stripos($useragent,"Macintosh");


    $DEVICE = ($iPod||$iPad||$iPhone||$iOS||$iPadOS);

    if (!$DEVICE) { ?>

    <script>
    AOS.init();
    </script>

    <?php }else{ 
    ?>

    <script>
    AOS.init({
        disable: true
    });
    </script>

    <?php } ?>
</body>

</html>