<!DOCTYPE html>
<html lang="hr">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-4EWR6743JP"></script>
    <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'G-4EWR6743JP');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Konoba Kolona | Cavtat</title>

    <meta name="description"
        content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
    <meta name="keywords" content="Restoran, Cavtat, Sviježa riba, Pristupačne cijene, Cavtat">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="Dejan Lukic">

    <meta property="og:type" content="restaurant">
    <meta property="og:title" content="Konoba Kolona | Cavtat">
    <meta property="og:description"
        content="Rezervirajte stol u restoranu sa širokom ponudom svježe ribe, morskih plodova i domaćih vina. Nalazimo se u Cavtatu, šarmantnom malom gradiću s dugom tradicijom.">
    <meta property="og:url" content="https://konobakolona.com/hr/welcome">
    <meta property="og:image" content="https://konobakolona.com/images/welcomephoto.jpg">
    <meta property="og:image:alt" content="Salata od hobotnice">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/menu">
    <meta property="restaurant:menu" content="https://konobakolona.com/hr/drinks">
    <meta property="restaurant:contact_info:website" content="https://konobakolona.com">
    <meta property="og:site_name" content="Konoba Kolona">

    <link href="../css/style.css" type="text/css" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link href="https://fonts.googleapis.com/css2?family=Varela&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Taviraj:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    <script type="text/javascript" src="../script/carousel.js"></script>
    <script type="text/javascript" src="../script/parallax.min.js"></script>
    <script src="https://kit.fontawesome.com/ccf2869940.js" crossorigin="anonymous"></script>

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Restaurant",
        "name": "Konoba Kolona",
        "image": "https://konobakolona.com/images/welcomephoto.jpg",
        "telephone": "+38520478787",
        "email": "konobakolona@gmail.com",
        "address": {
            "@type": "PostalAddress",
            "addressLocality": "Cavtat"
        },
        "menu": "https://konobakolona.com/hr/menu",
        "servesCuisine": "Morski plodovi",
        "url": "https://konobakolona.com/",
        "priceRange": "$$"
    }
    </script>
</head>

<body>
    <?php include('../templates/header_hr.php'); ?>

    <div class="parallax" data-parallax="scroll" data-speed="0.5" data-image-src="../images/welcomephoto.jpg"
        alt="Konoba Kolona Dobro došli">
        <h4>Ne radimo do sljedeće sezone!</h4>
    </div>
    <div class="container">

        <section class="contwrap">
            <div class="cont">
                <div class="icons" data-aos="flip-left" data-aos-duration="1500" data-aos-offset="300"><i
                        class="fas fa-sun"></i><i class="fas fa-water"></i></div>
                <div class="text">
                    <div data-aos="zoom-in" data-aos-duration="1500" data-aos-offset="300">
                        <p>U šarmantnom, pitoresknom gradiću Cavtatu, 20ak kilometara udaljenom od starih dubrovačkih
                            zidina, još od 1985. godine, nalazi se prepoznatljivi restoran obitelji Vragolov. Konobu
                            Kolonu uspješno vodi njen vlasnik i ribar Đuro, poznatiji kao Braco, koji je zaslužan za
                            većinu riblje ponude iz jelovnika.</p>
                    </div>
                </div>
            </div>
            <div class="cont">
                <div data-aos="zoom-in" data-aos-duration="1500" data-aos-offset="300">
                    <img src="../images/slika2.jpg" alt="Restoran Konoba Kolona">
                </div>
            </div>
        </section>

        <section class="contwrap">
            <div class="cont">
                <div class="" data-aos="zoom-in" data-aos-duration="1500" data-aos-offset="300">
                    <img src="../images/hrana8.jpg" alt="Najbolja morska hrana">
                </div>
            </div>
            <div class="cont order">
                <div class="icons" data-aos="flip-left" data-aos-duration="1500" data-aos-offset="300"><i
                        class="fas fa-fish"></i><i class="fas fa-carrot"></i></div>
                <div class="text">
                    <div data-aos="zoom-in" data-aos-duration="1500" data-aos-offset="300">
                        <p>U konobi Koloni, svakodnevno možete uživati u raznovrsnoj ponudi svježe ribe i plodova mora,
                            biranim mesnim jelima, kao i povrću lokalnih uzgajivača. Uz bogat jelovnik, nudimo i à la
                            carte jela, ovisno o dnevnom ulovu i ponudi sa lokalnih tržnica.</p>
                    </div>
                </div>
            </div>
        </section>

        <section class="contwrap">
            <div class="cont">
                <div class="icons" data-aos="flip-left" data-aos-duration="1500" data-aos-offset="300"><i
                        class="fas fa-wine-bottle"></i><i class="fas fa-wine-glass"></i></div>
                <div class="text">
                    <div data-aos="zoom-in" data-aos-duration="1500" data-aos-offset="300">
                        <p>U ugodnom ambijentu, uz naša nezaboravljiva jela, nudimo i široku ponudu visoko kvalitetnih
                            domaćih i lokalnih vina. Ne smijemo zaboraviti ni na deserte poput Dubrovačke rozate ili
                            torte od rogača i čokolade, po staroj domaćoj recepturi.</p>
                    </div>
                </div>
            </div>
            <div class="cont">
                <div class="" data-aos="zoom-in" data-aos-duration="1500" data-aos-offset="200">
                    <img src="../images/wine.jpg" alt="Vino">
                </div>
            </div>
        </section>
        <section class="contwrap">
            <div class="conttestemonials">
                <div class="icons" data-aos="zoom-in" data-aos-duration="1500" data-aos-offset="300"><i
                        class="far fa-star"></i><i class="far fa-star"></i></div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Fantastic restaurant</h2>
                            <p>The food at this restaurant is outstanding, not cheap mind but worth the extra Kunas.
                                Lovely fish and steak dishes and a good choice of wines.</p>
                            <p>Date of visit: October 2019</p>
                            <a href="https://www.tripadvisor.com/ShowUserReviews-g303804-d2177485-r720465232-Konoba_Kolona-Cavtat_Konavle_Dubrovnik_Neretva_County_Dalmatia.html"
                                target="_blank" rel="noreferrer">https://www.tripadvisor.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Authentic and delicious</h2>
                            <p>We ate out every night in our recent week in Cavtat and Konoba Kolona was the best
                                experience. You don't get a harbour view but then you don't get hassled to enter and you
                                do get authentic really fresh fish and meat cooked beautifully in Croatian style with
                                little fuss and a touch of 'home cooking' feeling. It is just one street from the sea
                                (near the bus station) but has a pleasant dining room and lovely roof terrace. Service
                                was attentive and friendly and knowledgeable about what was going on in the kitchen. On
                                two visits we had a mixture of mixed fish which was probably the star of the show -
                                tasting 'caught same-day' fresh and served with beautifully homely potatoes and spinach.
                                We had previously had fish kebabs which were also wonderfully fresh and cleverly cooked
                                so the fish of all sorts were perfectly cooked, nothing under or over. Starters of
                                octopus salad and Dalmatian smoked ham with aragula (rocket) were just right.
                                Neighbouring tables having meat seemed equally pleased. Next time we visit Cavtat this
                                will be our first port of call to eat.</p>
                            <p>Date of visit: May 2018</p>
                            <a href="https://www.tripadvisor.com/ShowUserReviews-g303804-d2177485-r581951606-Konoba_Kolona-Cavtat_Konavle_Dubrovnik_Neretva_County_Dalmatia.html"
                                target="_blank" rel="noreferrer">https://www.tripadvisor.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Excellent seafood choices!</h2>
                            <p>We decided to have dinner at this Konoba based on the numerousgreat TA reviews, and it
                                was sensational! I wasn't that hungry so I opted for two starters, the lobster salad &
                                the shrimp tempura. Both were outstanding, the lobster was a very generous portion super
                                fresh & delicious, the tempura perfectly crispy & tender shrimp. My boyfriend had the
                                starter seafood combo of clams, mussels, scampi prepared Buzara style, which he thought
                                was great. He then had another seafood offering of raznjic, another 10! Our friend
                                started with the seafood soup & then had a delicious plat of John Dory fish with tasty
                                vegetables. The service was excellent as well! There are many restaurants in Cavtat,
                                this one is not to be missed!! Very highly recommended.</p>
                            <p>Date of visit: May 2019</p>
                            <a href="https://www.tripadvisor.com/ShowUserReviews-g303804-d2177485-r677603641-Konoba_Kolona-Cavtat_Konavle_Dubrovnik_Neretva_County_Dalmatia.html"
                                target="_blank" rel="noreferrer">https://www.tripadvisor.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Fresh seafood</h2>
                            <p>We had a delicious meal on our first visit this evening. My husband chose the fresh tuna
                                and I went for the swordfish..both of which according to our lovely waitress, Neda were
                                caught by the owner so very fresh.We were not disappointed! Can also recommend the
                                squash soup and fish soup as starters and the panna cotta dessert..Good white house wine
                                too. Lovely, unpretentious restaurant set back from the waterfront. Will definitely
                                revisit and would recommend.Thank you, Neda, chef and everyone.</p>
                            <p>Date of visit: August 2019</p>
                            <a href="https://www.tripadvisor.com/ShowUserReviews-g303804-d2177485-r697339740-Konoba_Kolona-Cavtat_Konavle_Dubrovnik_Neretva_County_Dalmatia.html"
                                target="_blank" rel="noreferrer">https://www.tripadvisor.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Fabulous late lunch</h2>
                            <p>We where recommend to visit this restaurant from Mario ( Sea Kayaking Cavtat)The food was
                                excellent and very well cooked . Great choices on the menu. A superb wine list to choose
                                from . Staff where very friendly and attentive. Would highly recommend this restaurant.
                            </p>
                            <p>Date of visit: July 2019</p>
                            <a href="https://www.tripadvisor.com/ShowUserReviews-g303804-d2177485-r685760254-Konoba_Kolona-Cavtat_Konavle_Dubrovnik_Neretva_County_Dalmatia.html"
                                target="_blank" rel="noreferrer">https://www.tripadvisor.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Finally a good meal in Cavtat</h2>
                            <p>Spent a week in Cavtat at the beginning of this month and the town it’s self is beautiful
                                and Croatia too but overall we found the food very expensive and not that nice. On our
                                last night our Kayak guide suggested we go to Konoba Kolona so we took his advice and we
                                were very grateful we did. The food was fresh and everything was amazing, we were a
                                party of 8 including a four year old and every one of us enjoyed our meal. At the end of
                                the evening there was not one thing left on our plates which was a change from the other
                                nights when we couldn’t even eat the food we ordered as it was so bad. The staff too
                                were fantastic and best of all it was about the same price we had been paying all week,
                                the only thing we regret is that we didn’t find it on our first night there.</p>
                            <p>Date of visit: June 2019</p>
                            <a href="https://www.tripadvisor.com/ShowUserReviews-g303804-d2177485-r684603142-Konoba_Kolona-Cavtat_Konavle_Dubrovnik_Neretva_County_Dalmatia.html"
                                target="_blank" rel="noreferrer">https://www.tripadvisor.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Fantastic for allergies</h2>
                            <p>Brilliant food & very romantic Made us feel very welcome I have lot allergies but they
                                was very helpful & made beautiful meal.</p>
                            <p>Date of visit: September 2019</p>
                            <a href="https://www.tripadvisor.com/ShowUserReviews-g303804-d2177485-r713173253-Konoba_Kolona-Cavtat_Konavle_Dubrovnik_Neretva_County_Dalmatia.html"
                                target="_blank" rel="noreferrer">https://www.tripadvisor.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="testemonials">
                    <div class="slides">
                        <blockquote>
                            <h2>Great food</h2>
                            <p>Owned and run by a local fisherman, if you like seafood this place is a must. However
                                don't rule out the meat options which are also superb. One of my favourite restaurants
                                in the world, numerous visits over the last 7 years never a bad meal. Highly
                                recommended.</p>
                            <p>Date of visit: 8 August 2019 </p>
                            <a href="https://www.facebook.com/pg/konobaKolona/reviews/?ref=page_internal"
                                target="_blank" rel="noreferrer">https://www.facebook.com</a>
                        </blockquote>
                    </div>
                </div>
                <div class="dot-container">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                    <span class="dot" onclick="currentSlide(4)"></span>
                    <span class="dot" onclick="currentSlide(5)"></span>
                    <span class="dot" onclick="currentSlide(6)"></span>
                    <span class="dot" onclick="currentSlide(7)"></span>
                    <span class="dot" onclick="currentSlide(8)"></span>
                </div>
            </div>
        </section>
        <?php include('../templates/footer.php'); ?>
    </div>
    <script type="text/javascript" src="../script/main.js"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <?php 
    
    $useragent = $_SERVER['HTTP_USER_AGENT']; 
    $iPod = stripos($useragent, "iPod"); 
    $iPad = stripos($useragent, "iPad"); 
    $iPhone = stripos($useragent, "iPhone"); 
    $iOS = stripos($useragent, "iOS");
    $iPadOS = stripos($useragent,"Macintosh");


    $DEVICE = ($iPod||$iPad||$iPhone||$iOS||$iPadOS);

    if (!$DEVICE) { ?>

    <script>
    AOS.init();
    </script>

    <?php }else{ 
    ?>

    <script>
    AOS.init({
        disable: true
    });
    </script>

    <?php } ?>
</body>

</html>